
// List of sectors for the assessment system
export const sectorList = [
  'Aerospace and Aviation',
  'Agriculture',
  'Apparel',
  'Automotive',
  'Beauty & Wellness',
  'BFSI',
  'Capital Goods',
  'Construction',
  'Cross Sectoral',
  'Domestic Workers',
  'Electronics',
  'Food Processing',
  'Furniture & Fittings',
  'Gem & Jewellery',
  'Green Jobs',
  'Handicrafts and Carpet',
  'Healthcare',
  'Hydrocarbon',
  'Information Technology Sector',
  'Infrastructure Equipment',
  'Instrumentation',
  'Iron and Steel',
  'IT-ITeS',
  'Leather',
  'Life Sciences',
  'Logistics',
  'Management',
  'Media & Entertainment',
  'Mining',
  'Plumbing',
  'Power',
  'PwD',
  'Retail',
  'Rubber',
  'Sports',
  'Telecom',
  'Textile',
  'Tourism & Hospitality'
];
